name: pokemon_flutter
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1
environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  
  
  cupertino_icons: ^1.0.6
  # infrastructure
  injectable: ^2.4.2
  get_it: ^7.7.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  go_router: ^14.2.0
  flutter_bloc: ^8.1.6
  meta: any
  package_info_plus: ^8.0.0
  dio: ^5.4.3+1
  shared_preferences: ^2.2.3
  google_fonts: ^6.2.1
  lottie: ^3.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.1
  
  
  
  
  
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  freezed: ^2.5.2
  json_serializable: ^6.8.0
flutter:
  
  
  
  uses-material-design: true

  assets:
    - assets/animations/