name: 'Build Docker Image for Flutter Web'
description: 'Build Docker image for Flutter web application'
inputs:
  web_build_path:
    description: 'The path to the Flutter web build directory'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Create Dockerfile
      shell: bash
      run: |
        echo 'FROM nginx:alpine' > Dockerfile
        echo 'COPY ${{ inputs.web_build_path }} /usr/share/nginx/html' >> Dockerfile
        echo 'COPY nginx.conf /etc/nginx/nginx.conf' >> Dockerfile
        echo 'EXPOSE 80' >> Dockerfile
        echo 'CMD ["nginx", "-g", "daemon off;"]' >> Dockerfile

    - name: Create nginx.conf
      shell: bash
      run: |
        echo 'server {' > nginx.conf
        echo '    listen 80;' >> nginx.conf
        echo '    server_name localhost;' >> nginx.conf
        echo '    location / {' >> nginx.conf
        echo '        try_files \$uri \$uri/ /index.html;' >> nginx.conf
        echo '    }' >> nginx.conf
        echo '    error_page 500 502 503 504 /50x.html;' >> nginx.conf
        echo '    location = /50x.html {' >> nginx.conf
        echo '        root /usr/share/nginx/html;' >> nginx.conf
        echo '    }' >> nginx.conf
        echo '}' >> nginx.conf

    - name: Package Web and Config Files
      shell: bash
      run: |
        mkdir release_files
        cp -r ${{ inputs.web_build_path }} release_files/web
        cp Dockerfile release_files/
        cp nginx.conf release_files/
        cd release_files
        zip -r web_release.zip .

    - name: Upload Web Package Artifact
      uses: actions/upload-artifact@v2
      with:
        name: web-release
        path: release_files/web_release.zip
