// Mocks generated by Mockito 5.4.4 from annotations
// in pokemon_flutter/test/domain/pokemon/get_pokemon_list_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pokemon_flutter/data/repository/pokemon/pokemon_repository.dart'
    as _i4;
import 'package:pokemon_flutter/domain/base/page_wrapper.dart' as _i2;
import 'package:pokemon_flutter/domain/pokemon/pokemon_entity.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePageWrapper_0<D> extends _i1.SmartFake
    implements _i2.PageWrapper<D> {
  _FakePageWrapper_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePokemonEntity_1 extends _i1.SmartFake implements _i3.PokemonEntity {
  _FakePokemonEntity_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PokemonRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPokemonRepository extends _i1.Mock implements _i4.PokemonRepository {
  @override
  _i5.Future<_i2.PageWrapper<_i3.PokemonEntity>> findAll(
    int? page,
    int? pageSize,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findAll,
          [
            page,
            pageSize,
          ],
        ),
        returnValue: _i5.Future<_i2.PageWrapper<_i3.PokemonEntity>>.value(
            _FakePageWrapper_0<_i3.PokemonEntity>(
          this,
          Invocation.method(
            #findAll,
            [
              page,
              pageSize,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.PageWrapper<_i3.PokemonEntity>>.value(
                _FakePageWrapper_0<_i3.PokemonEntity>(
          this,
          Invocation.method(
            #findAll,
            [
              page,
              pageSize,
            ],
          ),
        )),
      ) as _i5.Future<_i2.PageWrapper<_i3.PokemonEntity>>);

  @override
  _i5.Future<_i3.PokemonEntity> findById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #findById,
          [id],
        ),
        returnValue: _i5.Future<_i3.PokemonEntity>.value(_FakePokemonEntity_1(
          this,
          Invocation.method(
            #findById,
            [id],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.PokemonEntity>.value(_FakePokemonEntity_1(
          this,
          Invocation.method(
            #findById,
            [id],
          ),
        )),
      ) as _i5.Future<_i3.PokemonEntity>);
}
