name: CI
on:
  pull_request:
      branches:
        - main
  push:
    branches:
      - feature/cicd
jobs:
  run_tests:
    name: run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Flutter action
        uses: subosito/flutter-action@v2.9.x
        with:
          channel: stable
          flutter-version-file: pubspec.yaml # path to pubspec.yaml
      - run: flutter --version
      - run: flutter pub get
      - run: flutter pub run build_runner build --delete-conflicting-outputs
      - run: flutter test
      - run: flutter test




